### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by rubyzhao** [samdutton/multihouse#1]
To test this, only first line in input.csv was kept. The following message/errors come.
I use node v12.11.1; lighthouse:v5.6.0.

>>>>Run 1 of 3: URL 1 of 1
>>>> Caught error for https://www.acehardware.com:
TypeError: Cannot read property 'message' of undefined
Start run 2
Run 2 of 3: URL 1 of 1
>>>> Caught error for https://www.acehardware.com:
TypeError: Cannot read property 'message' of undefined
Start run 3
Run 3 of 3: URL 1 of 1
>>>> Caught error for https://www.acehardware.com:
TypeError: Cannot read property 'message' of undefined
(node:15028) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at getOutput (E:\MyDocuments\VisualStudio\WebDevelop\DevTools\Lighthouse\multihouse-master\src\index.js:240:33)
    at E:\MyDocuments\VisualStudio\WebDevelop\DevTools\Lighthouse\multihouse-master\src\index.js:213:37
    at <anonymous>
(node:15028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by samdutton** [comment]
Thanks for filing the issue! I'm traveling at the moment, but I'll take a look when I get back to the office.

**Comment by samdutton** [comment]
Thanks again for the heads up.

[This  commit](https://github.com/samdutton/multihouse/commit/fc9021a30b839160c6d0913de155ade36faa3dc7) should fix the problem you describe.

The problem AFAICT was that I was using an older version of Lighthouse, for which `results.runtimeError` was defined, even if `results.runtimeError.message` wasn't.

If you can, please try pulling the update and confirm that the fix works for you.

**Comment by samdutton** [comment]
No comments, so I'm assuming this is fixed. 

Feel free to reopen if necessary.

Thanks again!

**Comment by rubyzhao** [comment]
Thanks. It works now. Sorry for later to test it.

**Comment by samdutton** [comment]
That's great — thanks for letting me know.
